//
//  SampleViewController.swift
//  Sourcery
//
//  Created by Vedran Burojevic on 23/09/2017.
//  Copyright (c) 2017 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SampleViewController: UIViewController {
	
	// MARK: - Public properties -
	
	var presenter: SamplePresenterInterface!
	
	// MARK: - Life cycle -
	
	override func viewDidLoad() {
		
	}
	
}

// MARK: - Extensions -

extension SampleViewController: SampleViewInterface {
	
	func showLoading() {
		
	}
	
	func hideLoading() {
		
	}
	
}
