//
//  SamplePresenter.swift
//  Sourcery
//
//  Created by Vedran Burojevic on 23/09/2017.
//  Copyright (c) 2017 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SamplePresenter {

    // MARK: - Private properties -

    fileprivate weak var _view: SampleViewInterface?
    fileprivate var _interactor: SampleInteractorInterface
    fileprivate var _wireframe: SampleWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: SampleWireframeInterface, view: SampleViewInterface, interactor: SampleInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension SamplePresenter: SamplePresenterInterface {
	
	func loadData() {
		
	}
	
}
