//
//  SampleInteractor.swift
//  Sourcery
//
//  Created by Vedran Burojevic on 23/09/2017.
//  Copyright (c) 2017 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SampleInteractor {
}

// MARK: - Extensions -

extension SampleInteractor: SampleInteractorInterface {
	
	func loadPokemons() {
		
	}
	
}
